package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	TOKEN_REQUEST, TOKEN, ALL_UPDATES_DONE, LIST_FILES, ADD_FRIEND, REMOVE_FILE, BACKUP, SEND_BACKUP,
	PING, PONG, IS_REALLY_DEAD, FAILURE_UPDATE
}
